[2024-03-15T09:48:50.202+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: example_sensors.week_day_sensor_failing_on_timeout manual__2024-03-15T09:46:41.562323+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
