[2024-03-18T08:07:47.461+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sftp_sync.sync_files_task manual__2024-03-18T08:06:39.668981+00:00 [queued]>
[2024-03-18T08:07:47.489+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sftp_sync.sync_files_task manual__2024-03-18T08:06:39.668981+00:00 [queued]>
[2024-03-18T08:07:47.491+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-03-18T08:07:48.597+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): sync_files_task> on 2024-03-18 08:06:39.668981+00:00
[2024-03-18T08:07:48.664+0000] {standard_task_runner.py:60} INFO - Started process 1448 to run task
[2024-03-18T08:07:48.684+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sftp_sync', 'sync_files_task', 'manual__2024-03-18T08:06:39.668981+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/sftp_sync_between_source_and_target.py', '--cfg-path', '/tmp/tmpbm4vkp80']
[2024-03-18T08:07:48.692+0000] {standard_task_runner.py:88} INFO - Job 84: Subtask sync_files_task
[2024-03-18T08:07:48.920+0000] {task_command.py:423} INFO - Running <TaskInstance: sftp_sync.sync_files_task manual__2024-03-18T08:06:39.668981+00:00 [running]> on host fa05d1b87173
[2024-03-18T08:07:49.300+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sftp_sync' AIRFLOW_CTX_TASK_ID='sync_files_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T08:06:39.668981+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T08:06:39.668981+00:00'
[2024-03-18T08:07:49.307+0000] {ssh.py:301} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-03-18T08:07:49.401+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-03-18T08:07:50.012+0000] {transport.py:1909} INFO - Authentication (password) successful!
[2024-03-18T08:07:50.173+0000] {sftp.py:169} INFO - [chan 0] Opened sftp connection (server version 3)
[2024-03-18T08:07:50.185+0000] {ssh.py:301} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-03-18T08:07:50.259+0000] {transport.py:1909} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2024-03-18T08:07:50.634+0000] {transport.py:1909} INFO - Authentication (password) successful!
[2024-03-18T08:07:50.744+0000] {sftp.py:169} INFO - [chan 0] Opened sftp connection (server version 3)
[2024-03-18T08:07:50.839+0000] {logging_mixin.py:188} INFO - Transforming files...
[2024-03-18T08:07:50.862+0000] {sftp_sync_between_source_and_target.py:35} INFO - Syncing file file1.txt...
[2024-03-18T08:07:50.873+0000] {python.py:202} INFO - Done. Returned value was: Synced 1 new files.
[2024-03-18T08:07:51.240+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sftp_sync, task_id=sync_files_task, execution_date=20240318T080639, start_date=20240318T080747, end_date=20240318T080751
[2024-03-18T08:07:51.653+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-18T08:07:51.851+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
